### ISSUE TITLE
Create component: contact form

### ISSUE THREAD

**Issue by ProcneDC** [MaatReef/clinicaMedica#15]

**Comment by MaatReef** [comment]
Lo podríamos agregar debajo del mapa principal.. Por encima del Footer.

**Comment by MaatReef** [comment]
Propuesta: Agregarlo arriba del pie de página, debajo del mapa principal.

**Comment by MaatReef** [comment]
Agregué Sweet Alert (Retroalimentación de mensajes ante escucha de eventos, el click al enviar el formulario de contacto)

https://sweetalert.js.org/docs/
